import torch
from src.manifolds.euclidean.vector import VectorEuclidean

class PullbackVectorEuclidean(VectorEuclidean):
    """ Base class describing a R^d under a pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, manifold, diffeomorphism):
        super().__init__(diffeomorphism.d)
        self.phi = diffeomorphism 
        self.manifold = manifold

    def barycentre(self, x, tol=None, max_iter=None, step_size=None, red_coef=None):
        """

        :param x: N x d
        :return: d
        """
        return self.phi.inverse(self.manifold.barycentre(self.phi.forward(x), tol=tol, max_iter=max_iter, step_size=step_size, red_coef=red_coef)[None])[0]

    def inner(self, x, X, Y):
        """

        :param x: N x d
        :param X: N x M x d
        :param Y: N x L x d
        :return: N x M x L
        """
        M = X.shape[1]
        L = Y.shape[1]
        return self.manifold.inner(self.phi.forward(x),
                                   self.phi.differential_forward((x[:, None].repeat(1,M,1)).reshape(-1, self.d), X.reshape(-1, self.d)).reshape(X.shape),
                                   self.phi.differential_forward((x[:, None].repeat(1,L,1)).reshape(-1, self.d), Y.reshape(-1, self.d)).reshape(Y.shape)
                                   )
    
    def norm(self, x, X):
        """

        :param x: N x d
        :param X: N x M x d
        :return: N x M
        """
        M = X.shape[1]
        
        phi_x = self.phi.forward(x)[:,None].repeat(1,M,1).reshape(-1, self.d)
        phi_X = self.phi.differential_forward((x[:, None].repeat(1,M,1)).reshape(-1, self.d), X.reshape(-1, self.d)).reshape(X.shape)
        return self.manifold.inner(phi_x, phi_X, phi_X).sqrt().reshape(-1, M)

    def geodesic(self, x, y, t):
        """

        :param x: N x M x d
        :param y: N x L x d
        :param t: K or N x M x L x K
        :return: N x M x L x K x d
        """
        N, M, d = x.shape
        L = y.shape[1]
        K = t.shape[-1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, d)).reshape(N, M, d) 
        phi_y = self.phi.forward(y.reshape(-1, d)).reshape(N, L, d) 

        # Weighted combination in phi-space
        phi_geo = self.manifold.geodesic(phi_x, phi_y, t)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_geo.reshape(-1, d)).reshape(N, M, L, K, d)
            
    def log(self, x, y): 
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L x d
        """
        N, M, d = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, d)).reshape(N, M, d) 
        phi_y = self.phi.forward(y.reshape(-1, d)).reshape(N, L, d) 

        # log in phi-space
        phi_log = self.manifold.log(phi_x, phi_y)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse(phi_x[:,:,None].repeat(1,1,L,1).reshape(-1, d),
                                             phi_log.reshape(-1, d)
                                             ).reshape(N, M, L, d)

    def exp(self, x, X): 
        """

        :param x: N x d
        :param X: N x M x d
        :return: N x M x d
        """
        N, d = x.shape
        M = X.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, d)).reshape(N, d) 
        phi_X = self.phi.differential_forward((x[:, None].repeat(1, M, 1)).reshape(-1, d), X.reshape(-1, d)).reshape(N, M, d)

        # exp in phi-space
        phi_exp = self.manifold.exp(phi_x, phi_X)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_exp.reshape(-1, d)).reshape(N, M, d)

    def distance(self, x, y):
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L
        """
        N, M, d = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, d)).reshape(N, M, d) 
        phi_y = self.phi.forward(y.reshape(-1, d)).reshape(N, L, d) 

        # distance in phi-space
        return self.manifold.distance(phi_x, phi_y).reshape(N, M, L)

    def parallel_transport(self, x, X, y):
        """

        :param x: N x M x d
        :param X: N x M x K x d
        :param y: N x L x d
        :return: N x M x L x K x d
        """
        N, M, d = x.shape
        L = y.shape[1]
        K = X.shape[2]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, d)).reshape(N, M, d)
        phi_y = self.phi.forward(y.reshape(-1, d)).reshape(N, L, d)
        phi_X = self.phi.differential_forward((x[:, :, None].repeat(1, 1, K, 1)).reshape(-1, d), X.reshape(-1, d)).reshape(N, M, K, d)

        # parallel transport in phi-space
        phi_pt = self.manifold.parallel_transport(phi_x, phi_X, phi_y).reshape(N, M, L, K, d)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse((phi_y[:, None].repeat(1, M, 1, K, 1)).reshape(-1, d), phi_pt.reshape(-1, d)).reshape(N, M, L, K, d)
        