from src.manifolds.euclidean.vector.pullback import PullbackVectorEuclidean
from src.manifolds.euclidean.vector.standard import StandardVectorEuclidean

class StandardPullbackVectorEuclidean(PullbackVectorEuclidean):
    """ Base class describing a R^d under a l^2-pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, diffeomorphism):
        super().__init__(StandardVectorEuclidean(diffeomorphism.d), diffeomorphism)