import torch
from src.manifolds.euclidean.sequence import SequenceEuclidean 

class PullbackSequenceEuclidean(SequenceEuclidean):
    """ Base class describing a R^d under a pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, sequence_manifold, sequence_diffeomorphism):
        super().__init__(sequence_diffeomorphism.C, sequence_diffeomorphism.L)
        self.phi = sequence_diffeomorphism
        self.manifold = sequence_manifold

    def barycentre(self, x, tol=None, max_iter=None, step_size=None, red_coef=None):
        """

        :param x: N x (C x L) 
        :return: (C x L) 
        """
        return self.phi.inverse(self.manifold.barycentre(self.phi.forward(x), tol=tol, max_iter=max_iter, step_size=step_size, red_coef=red_coef)[None])[0]

    def inner(self, x, X, Y):
        """

        :param x: N x (C x L) 
        :param X: N x M x (C x L) 
        :param Y: N x I x (C x L) 
        :return: N x M x I
        """
        M = X.shape[1]
        I = Y.shape[1]
        return self.manifold.inner(self.phi.forward(x),
                                   self.phi.differential_forward((x[:, None].repeat(1,M,1,1)).reshape(-1, self.C, self.L), X.reshape(-1, self.C, self.L)).reshape(X.shape),
                                   self.phi.differential_forward((x[:, None].repeat(1,I,1,1)).reshape(-1, self.C, self.L), Y.reshape(-1, self.C, self.L)).reshape(Y.shape)
                                   )

    def geodesic(self, x, y, t): 
        """

        :param x: N x M x (C x L) 
        :param y: N x I x (C x L) 
        :param t: K or N x M x L x K
        :return: N x M x I x K x (C x L)
        """
        N, M, C, L = x.shape
        I = y.shape[1]
        K = t.shape[-1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, L)).reshape(N, M, C, L) 
        phi_y = self.phi.forward(y.reshape(-1, C, L)).reshape(N, I, C, L) 

        # Weighted combination in phi-space
        phi_geo = self.manifold.geodesic(phi_x, phi_y, t)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_geo.reshape(-1, C, L)).reshape(N, M, I, K, C, L)

    def log(self, x, y): 
        """

        :param x: N x M x (C x L)
        :param y: N x I x (C x L)
        :return: N x M x I x (C x L)
        """
        N, M, C, L = x.shape
        I = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, L)).reshape(N, M, C, L) 
        phi_y = self.phi.forward(y.reshape(-1, C, L)).reshape(N, I, C, L) 

        # log in phi-space
        phi_log = self.manifold.log(phi_x, phi_y)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse(phi_x[:,:,None].repeat(1,1,I,1,1).reshape(-1, C, L),
                                             phi_log.reshape(-1, C, L)
                                             ).reshape(N, M, I, C, L)

    def exp(self, x, X): 
        """

        :param x: N x (C x L)
        :param X: N x M x (C x L)
        :return: N x M x (C x L)
        """
        N, C, L = x.shape
        M = X.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, L)).reshape(N, C, L) 
        phi_X = self.phi.differential_forward((x[:, None].repeat(1, M, 1, 1)).reshape(-1, C, L), X.reshape(-1, C, L)).reshape(N, M, C, L)

        # exp in phi-space
        phi_exp = self.manifold.exp(phi_x, phi_X)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_exp.reshape(-1, C, L)).reshape(N, M, C, L)

    def distance(self, x, y):
        """

        :param x: N x M x (C x L)
        :param y: N x I x (C x L)
        :return: N x M x I
        """
        N, M, C, L = x.shape
        I = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, L)).reshape(N, M, C, L) 
        phi_y = self.phi.forward(y.reshape(-1, C, L)).reshape(N, I, C, L) 

        # distance in phi-space
        return self.manifold.distance(phi_x, phi_y).reshape(N, M, I)

    def parallel_transport(self, x, X, y): 
        """

        :param x: N x M x (C x L)
        :param X: N x M x I x K x (C x L)
        :param y: N x I x (C x L)
        :return: N x M x I x K x (C x L)
        """
        N, M, C, L = x.shape
        I = y.shape[1]
        K = X.shape[2]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, L)).reshape(N, M, C, L)
        phi_y = self.phi.forward(y.reshape(-1, C, L)).reshape(N, I, C, L)
        phi_X = self.phi.differential_forward((x[:, :, None, None].repeat(1, 1, I, K, 1, 1)).reshape(-1, C, L), X.reshape(-1, C, L)).reshape(N, M, I, K, C, L)

        # parallel transport in phi-space
        phi_pt = self.manifold.parallel_transport(phi_x, phi_X, phi_y).reshape(N, M, I, K, C, L)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse((phi_y[:, None].repeat(1, M, 1, K, 1, 1)).reshape(-1, C, L), phi_pt.reshape(-1, C, L)).reshape(N, M, I, K, C, L)
    