from src.manifolds.euclidean.sequence.pullback import PullbackSequenceEuclidean
from src.manifolds.euclidean.sequence.standard import StandardSequenceEuclidean

class StandardPullbackSequenceEuclidean(PullbackSequenceEuclidean):
    """ Base class describing a R^d under a l^2-pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, sequence_diffeomorphism):
        super().__init__(StandardSequenceEuclidean(sequence_diffeomorphism.C, sequence_diffeomorphism.L), sequence_diffeomorphism)