from src.manifolds.euclidean.image.pullback import PullbackImageEuclidean
from src.manifolds.euclidean.image.standard import StandardImageEuclidean

class StandardPullbackImageEuclidean(PullbackImageEuclidean):
    """ Base class describing a R^d under a l^2-pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, image_diffeomorphism):
        super().__init__(StandardImageEuclidean(image_diffeomorphism.C, image_diffeomorphism.H, image_diffeomorphism.W), image_diffeomorphism)